import datetime
x = datetime.datetime.now()
print(x)
print(x.year)
print(x.month)
print(x.day)
print(x.strftime("%A"))
a = min(48, 392, 93)
b = max(90,929,4839)
print(a)
print(b)
c = abs(-987)
print(c)
d = pow(6, 4)
print(d)
import math
g = math.sqrt(9)
print(int(g))
x = math.ceil(2.46)
y = math.floor(2.45)
print(x)
print(y)